version: '3.9'

services:
  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  celery:
    build: ./app
    command: poetry run celery -A project worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env
    restart: always

  celery-beat:
    build: ./app
    command: poetry run celery -A project beat --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env
    restart: always

volumes:
  db-data: