# Generated by Django 5.2.1 on 2025-06-25 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBankSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_code", models.CharField(max_length=10)),
                ("agency", models.CharField(max_length=10)),
                ("account", models.CharField(max_length=20)),
                ("account_digit", models.CharField(max_length=5)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Conta Corrente"),
                            ("SAVINGS", "Conta Poupança"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
