# Generated by Django 5.2.1 on 2025-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userbanksettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbanksettings",
            name="asaas_recipient_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
