# Generated by Django 5.2.1 on 2025-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userbanksettings_asaas_recipient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
