# Generated by Django 5.2.1 on 2025-07-01 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbanksettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
