# Generated by Django 5.2.1 on 2025-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charge",
            name="debtor",
        ),
        migrations.AddField(
            model_name="charge",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="charge",
            name="name",
            field=models.CharField(default="no name", max_length=50),
        ),
        migrations.AddField(
            model_name="charge",
            name="phone",
            field=models.CharField(default="no phone", max_length=11),
        ),
        migrations.AddField(
            model_name="charge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="Debtor",
        ),
    ]
