# Generated by Django 5.2.1 on 2025-06-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_charge_debtor_charge_email_charge_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="charge",
            field=models.ForeignKey(
                default="57c51aed-7fbf-4d15-b6fa-04238add82de",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.charge",
            ),
            preserve_default=False,
        ),
    ]
