# Generated by Django 5.2.1 on 2025-06-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="whatsapp_authorized",
            field=models.BooleanField(default=False),
        ),
    ]
