# Generated by Django 5.2.1 on 2025-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_charge_whatsapp_authorized"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("max_active_charges", models.PositiveIntegerField()),
                ("allowed_channels", models.JSONField(default=list)),
                ("weekly_charge_limit", models.PositiveIntegerField()),
                ("priority_support", models.BooleanField(default=False)),
                ("allow_installments", models.BooleanField(default=False)),
            ],
        ),
    ]
