# Generated by Django 5.2.1 on 2025-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charge",
            name="installment_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
