# Generated by Django 5.2.1 on 2025-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_charge_asaas_id_charge_invoice_url_asaascustomer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asaascustomer",
            unique_together={("email", "phone")},
        ),
        migrations.AddField(
            model_name="asaascustomer",
            name="cpfCnpj",
            field=models.CharField(default=10910246777, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charge",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charge",
            name="phone",
            field=models.CharField(default="no phone", max_length=15),
        ),
        migrations.AlterField(
            model_name="charge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente de aceite"),
                    ("aceita", "Aceita e enviada"),
                    ("recusada", "Recusada pelo devedor"),
                    ("cancelada", "Cancelada pelo cobrador"),
                    ("paga", "Paga"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="asaascustomer",
            name="user",
        ),
    ]
