# Generated by Django 5.2.1 on 2025-07-01 13:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_asaascustomer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="aceite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
